### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by dgrisham** [dgrisham/wenv#2]
Need more examples of useful wenv ideas

**Comment by dgrisham** [comment]
https://github.com/dgrisham/wenv/commit/b47659f269f50323dd8966308ccab9bcbde5233f partially addressed this with the `http-2` wenv. Still need other examples with `shutdown_wenv()` and `bootstrap_wenv()`.

**Comment by jmpohl** [comment]
I think the examples are also a bit out of date. They define the edit and c extensions in the wenv when they don't really need to?

**Comment by dgrisham** [comment]
Good catch, addressed by https://github.com/dgrisham/wenv/pull/33.

**Comment by dgrisham** [comment]
Closing because this issue is vague and unaddressed.
