### ISSUE TITLE
c extension: add subdirectory as subdir of arg, including completion

### ISSUE THREAD

**Issue by dgrisham** [dgrisham/wenv#29]
`c results/bvjkqtmo0u3pc30sj8q0`

subdirectories of `$wenv_dirs[results]` should tab-complete

**Comment by jmpohl** [comment]
Good work around is adding additional values to the `wenv_dirs` associative array with dashes. you can tab complete up to a dash easily and subsequent tab presses put you into the addition dirs. Example:

```
declare -Ag wenv_dirs=(
        [forecasting]=smart-forecasting
        [forecasting-app]=smart-forecasting/app
        [forecasting-app-src]=/smart-forecasting/app/src
)
```

Allows tab completion to work mostly like you would expect. Takes additional configuration, but it addresses my use cases
