### ISSUE TITLE
Document layouts

### ISSUE THREAD

**Issue by dgrisham** [dgrisham/wenv#4]
[Layouts](https://github.com/dgrisham/wenv/blob/b57186d7cc0c07e0b572d26d5ebdeaf8cc70770f/wenv#L742) are useful, but currently undocumented. Should also consider breaking layouts out of the main wenv file and have a system for users to create/include their own.

**Comment by jmpohl** [comment]
Any more thoughts on this? I mess around with it a bit and I would agree it makes sense to split it out of the main wenv file

**Comment by dgrisham** [comment]
I take it back, layouts weren't that useful. I tend to just copy/paste this stuff, it's like 3 lines per wenv and easier to see what's happening if you just have the tmux commands right in `wenv_start`. Happy to revisit this if there's interest in an extension but closing for now.
