### ISSUE TITLE
c Extension Completion Jank

### ISSUE THREAD

**Issue by jmpohl** [dgrisham/wenv#43]
When tab completing with and empty `wenv_dirs` associative array I get the following error

```bash
(rss)
josie at L0000995 in ~
$ c
_bash_complete:14: bad set of key/value pairs for associative array
_bash_complete:14: bad set of key/value pairs for associative array
_bash_complete:14: bad set of key/value pairs for associative array
```

Getting it three times really makes me wonder...

**Comment by dgrisham** [comment]
Hm, I can't repro this. What's your `wenv_dirs` declaration look like?

**Comment by jmpohl** [comment]
I can't either now.... Closing this :\

**Comment by jmpohl** [comment]
j
